import type { Lingua } from "./traduzioni";

export type Sezione = { id: string; titolo: string; testo: string[]; punti?: string[] };

export const GUIDA: Record<Lingua, Sezione[]> = {
  it: [
    { id: "scopo", titolo: "1. Scopo e base normativa", testo: ["Il programma calcola la percentuale di riciclabilità in massa di un imballaggio e ne attribuisce il grado di prestazione secondo il Reg. (UE) 2025/40 (PPWR), Allegato II, Tabella 3. Il report finale è pensato per il fascicolo tecnico (Allegato VII)."] },
    { id: "calcolo", titolo: "2. Come si calcola", testo: ["Per ogni componente: massa riciclabile = peso × % riciclabile ÷ 100. Poi:"], punti: ["Massa totale = somma dei pesi (in grammi)", "Massa riciclabile = somma delle masse riciclabili", "Riciclabilità % = massa riciclabile ÷ massa totale × 100"] },
    { id: "soglie", titolo: "3. Gradi e soglie", testo: ["Il grado è assegnato in tempo reale:"], punti: ["Grado A: ≥ 95% — Eccellenza", "Grado B: ≥ 80% — Alta riciclabilità", "Grado C: ≥ 70% — Soglia minima di ammissibilità", "Sotto il 70%: non conforme / non ammesso"] },
    { id: "dati", titolo: "4. Account e dati", testo: ["Per usare il programma si accede con un account. Valutazioni, dati aziendali e logo sono salvati online e sincronizzati tra i tuoi dispositivi; ciascun utente vede solo i propri dati.", "Nell'editor il salvataggio è automatico, con nuovi tentativi se la rete cade. Conserva comunque i report PDF e i file JSON delle valutazioni approvate."] },
    { id: "azienda", titolo: "5. Impostazioni azienda", testo: ["Dal menu in alto apri Impostazioni e compila:"], punti: ["Ragione sociale, Partita IVA, Sede", "Referente tecnico ed Email", "Logo: carica un'immagine (PNG o JPG); viene ridotta automaticamente. Puoi sostituirla o rimuoverla quando vuoi", "Premi Salva: compare la conferma"] },
    { id: "archivio", titolo: "6. Elenco valutazioni", testo: ["La schermata Valutazioni mostra titolo, revisione, data, massa totale, % e grado di ogni scheda. Azioni disponibili:"], punti: ["Nuova valutazione: crea una scheda con un esempio modificabile", "Modifica (clic sul titolo o sulla matita)", "Report: apre il documento finale", "Duplica: copia la scheda per una nuova revisione", "Esporta / Importa JSON: scambio o backup delle schede", "Elimina: rimozione definitiva"] },
    { id: "editor", titolo: "7. Editor: distinta base", testo: ["Imposta nome, revisione (es. REV 01) e data. Per ogni componente indica:"], punti: ["Componente e Materiale (es. serbatoio, AISI 304)", "Peso in grammi (punto o virgola, max due decimali)", "% riciclabile da 0 a 100: 100 per materiali omogenei con filiera UE, 0 per elastomeri, termoindurenti o plastiche miste senza filiera, valore intermedio solo se certificato", "La massa riciclabile di ogni riga è calcolata da sola", "+ Aggiungi componente / × per eliminare", "Note tecniche: ipotesi, codici disegno, norme adottate"] },
    { id: "risultato", titolo: "8. Leggere il risultato", testo: ["Il pannello a destra mostra in tempo reale la percentuale, la barra con le tacche 70% / 80% / 95% e il badge del grado. Da 70% in su la scheda è ammessa; sotto il 70% è segnalata come non conforme."] },
    { id: "report", titolo: "9. Report e PDF", testo: ["Con Esporta report si apre l'anteprima: intestazione con logo e dati aziendali, bilancio di massa, esito, classi di prestazione, note tecniche. Premi Scarica PDF; Luogo, Data e Referente/Firma si compilano nel PDF scaricato."] },
  ],
  en: [
    { id: "scopo", titolo: "1. Purpose and legal basis", testo: ["The program calculates the recyclability of a packaging by mass and assigns its performance grade under Reg. (EU) 2025/40 (PPWR), Annex II, Table 3. The final report is designed for the technical file (Annex VII)."] },
    { id: "calcolo", titolo: "2. How it is calculated", testo: ["For each component: recyclable mass = weight × recyclable % ÷ 100. Then:"], punti: ["Total mass = sum of weights (in grams)", "Recyclable mass = sum of recyclable masses", "Recyclability % = recyclable mass ÷ total mass × 100"] },
    { id: "soglie", titolo: "3. Grades and thresholds", testo: ["The grade is assigned in real time:"], punti: ["Grade A: ≥ 95% — Excellence", "Grade B: ≥ 80% — High recyclability", "Grade C: ≥ 70% — Minimum eligibility threshold", "Below 70%: non-compliant / not admitted"] },
    { id: "dati", titolo: "4. Account and data", testo: ["You sign in with an account. Assessments, company data and logo are saved online and synchronised across your devices; each user sees only their own data.", "In the editor, saving is automatic, with retries if the connection drops. Still keep the PDF reports and JSON files of approved assessments."] },
    { id: "azienda", titolo: "5. Company settings", testo: ["From the top menu open Settings and fill in:"], punti: ["Company name, VAT number, Address", "Technical contact and Email", "Logo: upload an image (PNG or JPG); it is reduced automatically. You can replace or remove it at any time", "Press Save: a confirmation appears"] },
    { id: "archivio", titolo: "6. Assessment list", testo: ["The Assessments screen shows title, revision, date, total mass, % and grade of each record. Available actions:"], punti: ["New assessment: creates a record with an editable example", "Edit (click the title or the pencil)", "Report: opens the final document", "Duplicate: copies the record for a new revision", "Export / Import JSON: exchange or back up records", "Delete: permanent removal"] },
    { id: "editor", titolo: "7. Editor: bill of materials", testo: ["Set name, revision (e.g. REV 01) and date. For each component enter:"], punti: ["Component and Material (e.g. tank, AISI 304)", "Weight in grams (point or comma, max two decimals)", "Recyclable % from 0 to 100: 100 for homogeneous materials with an EU stream, 0 for elastomers, thermosets or mixed plastics with no stream, an intermediate value only if certified", "The recyclable mass of each row is calculated automatically", "+ Add component / × to delete", "Technical notes: assumptions, drawing codes, standards adopted"] },
    { id: "risultato", titolo: "8. Reading the result", testo: ["The right-hand panel shows the percentage in real time, the bar with the 70% / 80% / 95% marks and the grade badge. From 70% upwards the record is admitted; below 70% it is flagged as non-compliant."] },
    { id: "report", titolo: "9. Report and PDF", testo: ["Export report opens the preview: header with logo and company data, mass balance, result, performance classes, technical notes. Press Download PDF; Place, Date and Contact/Signature are filled in on the downloaded PDF."] },
  ],
  de: [
    { id: "scopo", titolo: "1. Zweck und Rechtsgrundlage", testo: ["Das Programm berechnet die Recyclingfähigkeit einer Verpackung nach Masse und vergibt die Leistungsklasse gemäß Verordnung (EU) 2025/40 (PPWR), Anhang II, Tabelle 3. Der Bericht ist für die technische Dokumentation (Anhang VII) gedacht."] },
    { id: "calcolo", titolo: "2. Berechnung", testo: ["Je Bauteil: recycelbare Masse = Gewicht × recycelbarer Anteil in % ÷ 100. Dann:"], punti: ["Gesamtmasse = Summe der Gewichte (in Gramm)", "Recycelbare Masse = Summe der recycelbaren Massen", "Recyclingfähigkeit in % = recycelbare Masse ÷ Gesamtmasse × 100"] },
    { id: "soglie", titolo: "3. Klassen und Schwellenwerte", testo: ["Die Klasse wird in Echtzeit vergeben:"], punti: ["Klasse A: ≥ 95 % — Exzellenz", "Klasse B: ≥ 80 % — Hohe Recyclingfähigkeit", "Klasse C: ≥ 70 % — Mindestschwelle", "Unter 70 %: nicht konform / nicht zugelassen"] },
    { id: "dati", titolo: "4. Konto und Daten", testo: ["Die Anmeldung erfolgt mit einem Konto. Bewertungen, Firmendaten und Logo werden online gespeichert und zwischen Ihren Geräten synchronisiert; jeder Nutzer sieht nur seine eigenen Daten.", "Im Editor wird automatisch gespeichert, bei Verbindungsabbruch mit erneuten Versuchen. Bewahren Sie dennoch PDF-Berichte und JSON-Dateien freigegebener Bewertungen auf."] },
    { id: "azienda", titolo: "5. Firmeneinstellungen", testo: ["Öffnen Sie im oberen Menü Einstellungen und füllen Sie aus:"], punti: ["Firmenname, USt-IdNr., Sitz", "Technischer Ansprechpartner und E-Mail", "Logo: Bild hochladen (PNG oder JPG); es wird automatisch verkleinert. Jederzeit ersetz- oder entfernbar", "Auf Speichern klicken: eine Bestätigung erscheint"] },
    { id: "archivio", titolo: "6. Liste der Bewertungen", testo: ["Der Bildschirm Bewertungen zeigt Titel, Revision, Datum, Gesamtmasse, % und Klasse jedes Datenblatts. Verfügbare Aktionen:"], punti: ["Neue Bewertung: erstellt ein Datenblatt mit bearbeitbarem Beispiel", "Bearbeiten (Klick auf den Titel oder den Stift)", "Bericht: öffnet das fertige Dokument", "Duplizieren: kopiert das Datenblatt für eine neue Revision", "JSON exportieren / importieren: Austausch oder Sicherung", "Löschen: endgültig entfernen"] },
    { id: "editor", titolo: "7. Editor: Stückliste", testo: ["Name, Revision (z. B. REV 01) und Datum festlegen. Für jedes Bauteil angeben:"], punti: ["Bauteil und Werkstoff (z. B. Tank, AISI 304)", "Gewicht in Gramm (Punkt oder Komma, max. zwei Nachkommastellen)", "Recycelbarer Anteil von 0 bis 100: 100 für homogene Werkstoffe mit EU-Kette, 0 für Elastomere, Duroplaste oder Mischkunststoffe ohne Kette, Zwischenwert nur bei Zertifizierung", "Die recycelbare Masse jeder Zeile wird automatisch berechnet", "+ Bauteil hinzufügen / × zum Löschen", "Technische Hinweise: Annahmen, Zeichnungsnummern, angewandte Normen"] },
    { id: "risultato", titolo: "8. Ergebnis lesen", testo: ["Das rechte Feld zeigt in Echtzeit den Prozentwert, den Balken mit den Marken 70 % / 80 % / 95 % und das Klassen-Badge. Ab 70 % ist das Datenblatt zugelassen; darunter wird es als nicht konform gekennzeichnet."] },
    { id: "report", titolo: "9. Bericht und PDF", testo: ["Mit Bericht exportieren öffnet sich die Vorschau: Kopf mit Logo und Firmendaten, Massenbilanz, Ergebnis, Leistungsklassen, technische Hinweise. Auf PDF herunterladen klicken; Ort, Datum und Ansprechpartner/Unterschrift werden im heruntergeladenen PDF ausgefüllt."] },
  ],
  es: [
    { id: "scopo", titolo: "1. Finalidad y base normativa", testo: ["El programa calcula la reciclabilidad en masa de un embalaje y le asigna el grado de prestación según el Reg. (UE) 2025/40 (PPWR), Anexo II, Tabla 3. El informe final está pensado para el expediente técnico (Anexo VII)."] },
    { id: "calcolo", titolo: "2. Cómo se calcula", testo: ["Para cada componente: masa reciclable = peso × % reciclable ÷ 100. Después:"], punti: ["Masa total = suma de los pesos (en gramos)", "Masa reciclable = suma de las masas reciclables", "Reciclabilidad % = masa reciclable ÷ masa total × 100"] },
    { id: "soglie", titolo: "3. Grados y umbrales", testo: ["El grado se asigna en tiempo real:"], punti: ["Grado A: ≥ 95 % — Excelencia", "Grado B: ≥ 80 % — Alta reciclabilidad", "Grado C: ≥ 70 % — Umbral mínimo de admisibilidad", "Por debajo del 70 %: no conforme / no admitido"] },
    { id: "dati", titolo: "4. Cuenta y datos", testo: ["Se accede con una cuenta. Evaluaciones, datos de empresa y logotipo se guardan en línea y se sincronizan entre tus dispositivos; cada usuario ve solo sus propios datos.", "En el editor el guardado es automático, con reintentos si se corta la conexión. Conserva igualmente los informes PDF y los archivos JSON de las evaluaciones aprobadas."] },
    { id: "azienda", titolo: "5. Ajustes de empresa", testo: ["En el menú superior abre Ajustes y completa:"], punti: ["Razón social, NIF/IVA, Domicilio", "Responsable técnico y Correo electrónico", "Logotipo: sube una imagen (PNG o JPG); se reduce automáticamente. Puedes sustituirla o quitarla cuando quieras", "Pulsa Guardar: aparece la confirmación"] },
    { id: "archivio", titolo: "6. Lista de evaluaciones", testo: ["La pantalla Evaluaciones muestra título, revisión, fecha, masa total, % y grado de cada ficha. Acciones disponibles:"], punti: ["Nueva evaluación: crea una ficha con un ejemplo editable", "Editar (clic en el título o en el lápiz)", "Informe: abre el documento final", "Duplicar: copia la ficha para una nueva revisión", "Exportar / Importar JSON: intercambio o copia de seguridad", "Eliminar: borrado definitivo"] },
    { id: "editor", titolo: "7. Editor: lista de materiales", testo: ["Define nombre, revisión (p. ej. REV 01) y fecha. Para cada componente indica:"], punti: ["Componente y Material (p. ej. depósito, AISI 304)", "Peso en gramos (punto o coma, máx. dos decimales)", "% reciclable de 0 a 100: 100 para materiales homogéneos con cadena en la UE, 0 para elastómeros, termoestables o plásticos mezclados sin cadena, valor intermedio solo si está certificado", "La masa reciclable de cada fila se calcula sola", "+ Añadir componente / × para eliminar", "Notas técnicas: hipótesis, códigos de plano, normas adoptadas"] },
    { id: "risultato", titolo: "8. Leer el resultado", testo: ["El panel derecho muestra en tiempo real el porcentaje, la barra con las marcas 70 % / 80 % / 95 % y la insignia del grado. A partir del 70 % la ficha queda admitida; por debajo se señala como no conforme."] },
    { id: "report", titolo: "9. Informe y PDF", testo: ["Con Exportar informe se abre la vista previa: cabecera con logotipo y datos de empresa, balance de masa, resultado, clases de prestación, notas técnicas. Pulsa Descargar PDF; Lugar, Fecha y Responsable/Firma se completan en el PDF descargado."] },
  ],
};
