// ======================================================================
// Nome File: traduzioni.ts
// Percorso: src/lib/traduzioni.ts
// Revisione: Rev. 2
// Data/Ora: 2026-10-01 21:46
// ======================================================================

export const LINGUE = ["it", "en", "de", "es"] as const;
export type Lingua = (typeof LINGUE)[number];

export const NOMI_LINGUE: Record<Lingua, string> = {
  it: "Italiano",
  en: "English",
  de: "Deutsch",
  es: "Español",
};

export const LOCALE: Record<Lingua, string> = {
  it: "it-IT",
  en: "en-GB",
  de: "de-DE",
  es: "es-ES",
};

const it = {
  // Generale
  "app.nome": "Riciclabilità PPWR",
  "app.sottotitolo": "Determinazione % riciclabilità · Reg. (UE) 2025/40",
  "nav.valutazioni": "Valutazioni",
  "nav.impostazioni": "Impostazioni",
  "nav.esci": "Esci",
  "nav.chiudiApp": "Chiudi applicazione",
  "nav.esciCancella": "Esci e cancella tutto",
  "lingua.etichetta": "Lingua",
  "comune.caricamento": "Caricamento…",
  "comune.nonTrovata": "Valutazione non trovata.",
  "comune.logoAlt": "Logo azienda",
  "comune.sessioneScaduta": "Sessione scaduta: accedi di nuovo.",

  // Gradi
  "grado.label": "Grado",
  "grado.A": "Eccellenza",
  "grado.B": "Alta riciclabilità",
  "grado.C": "Soglia minima di ammissibilità",
  "esito.nonConforme": "Non conforme",
  "stato.ammesso": "Ammesso",
  "stato.nonAmmesso": "Non ammesso",

  // Root
  "root.404": "Pagina non trovata",
  "root.404testo": "La pagina che cerchi non esiste o è stata spostata.",
  "root.home": "Torna alla home",
  "root.errTitolo": "Questa pagina non si è caricata",
  "root.errTesto": "Qualcosa è andato storto. Prova ad aggiornare la pagina o torna alla home.",
  "root.riprova": "Riprova",

  // Landing
  "landing.titoloPagina": "Riciclabilità PPWR — Calcolo grado di riciclabilità imballaggi",
  "landing.accedi": "Accedi all'app",
  "landing.kicker": "Reg. (UE) 2025/40 · Allegato II",
  "landing.titolo": "Riciclabilità degli imballaggi, calcolata e documentata.",
  "landing.testo":
    "Componi l'imballaggio per componenti, ottieni la percentuale in massa e il grado PPWR in tempo reale, ed esporta un report tecnico intestato alla tua azienda. Tutto salvato online e sincronizzato tra i tuoi dispositivi.",
  "landing.inizia": "Inizia una valutazione",

  // Auth

  // Impostazioni
  "imp.titoloPagina": "Impostazioni azienda — Riciclabilità PPWR",
  "imp.titolo": "Dati dell'azienda che compila",
  "imp.sotto": "usati nell'intestazione dei report",
  "imp.ragioneSociale": "Ragione sociale",
  "imp.partitaIva": "Partita IVA",
  "imp.sede": "Sede",
  "imp.referente": "Referente tecnico",
  "imp.email": "Email / contatto",
  "imp.phRagioneSociale": "Nome dell'azienda S.r.l.",
  "imp.phPartitaIva": "IT00000000000",
  "imp.phSede": "Via, CAP, Città (PR)",
  "imp.phReferente": "Nome e ruolo",
  "imp.phEmail": "tecnico@azienda.it",
  "imp.salva": "Salva dati azienda",
  "imp.salvato": "Dati salvati",
  "imp.errSalvataggio": "Salvataggio non riuscito",
  "imp.logo": "Logo aziendale",
  "imp.nessunLogo": "Nessun logo caricato",
  "imp.carica": "Carica immagine",
  "imp.rimuovi": "Rimuovi logo",
  "imp.logoTroppoGrande": "Il logo supera 1,5 MB: usa un file più leggero.",
  "imp.notaLogo":
    "PNG o JPG, max 1,5 MB. Dati e logo sono salvati online e disponibili su tutti i tuoi dispositivi.",

  // Elenco valutazioni
  "val.titoloPagina": "Valutazioni di riciclabilità — Riciclabilità PPWR",
  "val.nuova": "Nuova valutazione",
  "val.archivio": "Archivio valutazioni",
  "val.documenti": "{n} documenti · sincronizzati online",
  "val.vuotoTitolo": "Nessuna valutazione presente",
  "val.vuotoTesto":
    "Crea la prima valutazione: inserisci i componenti dell'imballaggio con peso e indice di riciclabilità, il grado PPWR viene calcolato automaticamente.",
  "val.colValutazione": "Valutazione",
  "val.colRevisione": "Revisione",
  "val.colMassa": "Massa (g)",
  "val.colRicic": "Riciclabilità",
  "val.colGrado": "Grado",
  "val.report": "Report",
  "val.modifica": "Modifica",
  "val.duplica": "Duplica",
  "val.elimina": "Elimina",
  "val.copia": "{titolo} (copia)",
  "val.confermaElimina": 'Eliminare "{titolo}"?',
  "val.errCrea": "Creazione non riuscita",
  "val.errDuplica": "Duplicazione non riuscita",
  "val.revisioneIniziale": "REV 01",

  // Esportazione / importazione JSON
  "json.esporta": "Esporta JSON",
  "json.importa": "Importa JSON",
  "json.esportato": "File esportato: {nome}",
  "json.importato": "Valutazione importata: {titolo}",
  "json.chiediAzienda":
    "Il file contiene i dati dell'azienda «{nome}», diversi da quelli attuali.\n\nVuoi aggiornare anche le impostazioni aziendali (dati e logo)?",
  "json.aziendaAggiornata": "Impostazioni aziendali aggiornate.",
  "json.descrizioneFile": "File di valutazione PPWR",
  "json.errEsportazione": "Esportazione non riuscita",
  "json.errImportazione": "Importazione non riuscita",
  "json.errFileNonJson": "Il file non è un JSON valido.",
  "json.errFormato": "Il file non è conforme allo standard PPWR.",
  "json.errVersione": "Versione del file non supportata: attesa {v}.",
  "json.errCampi": "Mancano titolo, data o un elenco di componenti valido.",
  "json.errComponente": "Il componente n. {n} ha peso o indice di riciclabilità non validi.",
  "json.errTroppoGrande": "Il file è troppo grande (max 5 MB).",

  // Componenti di esempio
  "demo.bottiglia": "Bottiglia",
  "demo.tappo": "Tappo",
  "demo.etichetta": "Etichetta",
  "demo.cartaMetallizzata": "Carta metallizzata",

  // Editor
  "ed.titoloPagina": "Editor valutazione — Riciclabilità PPWR",
  "ed.esporta": "Esporta report",
  "ed.salvato": "✓ salvato online",
  "ed.errSalvataggio": "errore di salvataggio",
  "ed.riprova": "Riprova ora",
  "ed.nuovoTentativo": "nuovo tentativo in corso…",
  "ed.salvataggio": "salvataggio…",
  "ed.componenti": "Componenti — bilancio di massa",
  "ed.righe": "{n} righe · massa totale {peso} g",
  "ed.colComponente": "Componente",
  "ed.colMateriale": "Materiale",
  "ed.colPeso": "Peso (g)",
  "ed.colPercRicic": "% ricic.",
  "ed.colMassaRicic": "Massa ricic. (g)",
  "ed.totale": "Totale",
  "ed.aggiungi": "+ Aggiungi componente",
  "ed.nuovoComponente": "Nuovo componente",
  "ed.calcolata": "Riciclabilità calcolata",
  "ed.gRiciclabili": "{m} g riciclabili su {t} g",
  "ed.sogliaMin": "Soglia minima di ammissibilità 2030:",
  "ed.soglie": "Soglie Allegato II Tab. 3",
  "ed.note": "Note tecniche",
  "ed.notePlaceholder":
    "Ipotesi di calcolo, riferimenti alla distinta base, scomposizione componenti complessi…",

  // Report
  "rep.titoloPagina": "Report di riciclabilità — Riciclabilità PPWR",
  "rep.stampa": "Scarica PDF",
  "ed.notaNumeri": "Numeri: puoi digitare punto o virgola (viene convertito in virgola, es. 2,5), al massimo due decimali. Peso in grammi; % riciclabile da 0 a 100.",
  "rep.generazione": "Generazione dell'anteprima…",
  "rep.errPdf": "Impossibile generare l'anteprima del PDF.",
  "rep.errScarica": "Impossibile generare il PDF.",
  "rep.notaAnteprima": "L'anteprima è in sola lettura: Luogo, Data e Referente si compilano nel PDF scaricato.",
  "rep.norma": "Regolamento (UE) 2025/40 (PPWR)",
  "rep.firmaTitolo": "Luogo, data e firma",
  "rep.luogo": "Luogo",
  "rep.data": "Data",
  "rep.firma": "Firma",
  "rep.pagina": "Pagina {n} di {tot}",
  "rep.anteprima": "Anteprima report",
  "rep.torna": "← torna all'editor",
  "rep.aziendaNonImpostata": "Azienda non impostata",
  "rep.aziendaNonImpostataMin": "azienda non impostata",
  "rep.piva": "P.IVA {v}",
  "rep.referente": "Referente: {v}",
  "rep.impostaDati": "Imposta i dati azienda",
  "rep.titolo": "Valutazione della riciclabilità dell'imballaggio",
  "rep.intro":
    "La presente relazione determina la quota di riciclabilità su base ponderale dell'imballaggio in oggetto ai sensi del Regolamento (UE) 2025/40 (PPWR). La percentuale è calcolata come rapporto tra la massa dei componenti riciclabili e la massa totale dell'imballaggio, secondo le classi di prestazione dell'Allegato II, Tabella 3.",
  "rep.s1": "1. Bilancio di massa",
  "rep.colIndice": "Indice (%)",
  "rep.totaleImballaggio": "Totale imballaggio",
  "rep.s2": "2. Esito del calcolo",
  "rep.ricic": "Riciclabilità",
  "rep.statoAmmissibilita": "Stato di ammissibilità dal 2030: {stato}",
  "rep.s3": "3. Classi di prestazione (Allegato II, Tabella 3)",
  "rep.s4": "4. Note tecniche",
  "rep.footer":
    "Documento generato per il fascicolo tecnico di cui all'Allegato VII del Reg. (UE) 2025/40 — {azienda}",
  "ed.etNome": "Nome imballaggio / prodotto",
  "ed.phNome": "es. Bottiglia in vetro, Tubetto dentifricio, Flacone PET 500 ml",
  "ed.etRevisione": "Revisione",
  "ed.etData": "Data",
  "ed.salva": "Salva",
  "ed.salvataggioOk": "Valutazione salvata con successo!",
  "ed.chiediNomeTitolo": "Assegna un nome alla valutazione",
  "ed.chiediNomeTesto":
    "Per archiviare correttamente la scheda, inserisci il nome del manufatto o imballaggio analizzato:",
  "ed.annulla": "Annulla",
  "ed.confermaSalva": "Conferma e salva",
  "ed.nomeObbligatorio": "Inserisci un nome diverso da «Nuova valutazione».",

  "nav.guida": "Guida",
  "guida.titoloPagina": "Guida — Riciclabilità PPWR",
  "guida.titolo": "Guida all'uso",
  "guida.intro": "Come funziona il programma, dal calcolo al report PDF.",
  "guida.sommario": "Indice",
  "guida.torna": "← torna all'app",
  "guida.avviso": "Strumento di supporto al calcolo: verifica sempre classi e soglie sul testo ufficiale del Reg. (UE) 2025/40.",
  "hint.apri": "Mostra suggerimento",
  "hint.revisione": "Codice di revisione del documento, ad es. REV 01, REV 02. Compare nel report.",
  "hint.componente": "Parte dell'imballaggio: ad es. serbatoio, valvola, guarnizione, tappo.",
  "hint.materiale": "Designazione del materiale: ad es. PET, HDPE, AISI 304, EPDM.",
  "hint.peso": "Massa del componente in grammi. Punto o virgola, al massimo due decimali.",
  "hint.indice": "Quota riciclabile da 0 a 100. 100 per materiali omogenei con filiera di riciclo in UE; 0 per elastomeri, termoindurenti o plastiche miste senza filiera; un valore intermedio solo se certificato.",
  "hint.massa": "Calcolata in automatico: peso × % riciclabile ÷ 100.",
  "hint.note": "Ipotesi di calcolo, codici disegno, scomposizione degli assiemi, norme adottate. Compaiono nella sezione 4 del report.",
};

export type Chiave = keyof typeof it;

const en: Record<Chiave, string> = {
  "app.nome": "PPWR Recyclability",
  "app.sottotitolo": "Recyclability % assessment · Reg. (EU) 2025/40",
  "nav.valutazioni": "Assessments",
  "nav.impostazioni": "Settings",
  "nav.esci": "Sign out",
  "nav.chiudiApp": "Close application",
  "nav.esciCancella": "Sign out and clear everything",
  "lingua.etichetta": "Language",
  "comune.caricamento": "Loading…",
  "comune.nonTrovata": "Assessment not found.",
  "comune.logoAlt": "Company logo",
  "comune.sessioneScaduta": "Session expired: please sign in again.",

  "grado.label": "Grade",
  "grado.A": "Excellence",
  "grado.B": "High recyclability",
  "grado.C": "Minimum eligibility threshold",
  "esito.nonConforme": "Non-compliant",
  "stato.ammesso": "Admitted",
  "stato.nonAmmesso": "Not admitted",

  "root.404": "Page not found",
  "root.404testo": "The page you're looking for doesn't exist or has been moved.",
  "root.home": "Go home",
  "root.errTitolo": "This page didn't load",
  "root.errTesto": "Something went wrong. You can try refreshing or head back home.",
  "root.riprova": "Try again",

  "landing.titoloPagina": "PPWR Recyclability — Packaging recyclability grade calculator",
  "landing.accedi": "Open the app",
  "landing.kicker": "Reg. (EU) 2025/40 · Annex II",
  "landing.titolo": "Packaging recyclability, calculated and documented.",
  "landing.testo":
    "Build your packaging component by component, get the mass percentage and the PPWR grade in real time, and export a technical report headed with your company details. Everything is saved online and synced across your devices.",
  "landing.inizia": "Start an assessment",


  "imp.titoloPagina": "Company settings — PPWR Recyclability",
  "imp.titolo": "Details of the company preparing the report",
  "imp.sotto": "used in the report header",
  "imp.ragioneSociale": "Company name",
  "imp.partitaIva": "VAT number",
  "imp.sede": "Registered office",
  "imp.referente": "Technical contact",
  "imp.email": "Email / contact",
  "imp.phRagioneSociale": "Company name Ltd",
  "imp.phPartitaIva": "IT00000000000",
  "imp.phSede": "Street, ZIP code, City",
  "imp.phReferente": "Name and role",
  "imp.phEmail": "technical@company.com",
  "imp.salva": "Save company details",
  "imp.salvato": "Details saved",
  "imp.errSalvataggio": "Save failed",
  "imp.logo": "Company logo",
  "imp.nessunLogo": "No logo uploaded",
  "imp.carica": "Upload image",
  "imp.rimuovi": "Remove logo",
  "imp.logoTroppoGrande": "The logo exceeds 1.5 MB: please use a smaller file.",
  "imp.notaLogo":
    "PNG or JPG, max 1.5 MB. Details and logo are saved online and available on all your devices.",

  "val.titoloPagina": "Recyclability assessments — PPWR Recyclability",
  "val.nuova": "New assessment",
  "val.archivio": "Assessment archive",
  "val.documenti": "{n} documents · synced online",
  "val.vuotoTitolo": "No assessments yet",
  "val.vuotoTesto":
    "Create your first assessment: enter the packaging components with weight and recyclability index, and the PPWR grade is calculated automatically.",
  "val.colValutazione": "Assessment",
  "val.colRevisione": "Revision",
  "val.colMassa": "Mass (g)",
  "val.colRicic": "Recyclability",
  "val.colGrado": "Grade",
  "val.report": "Report",
  "val.modifica": "Edit",
  "val.duplica": "Duplicate",
  "val.elimina": "Delete",
  "val.copia": "{titolo} (copy)",
  "val.confermaElimina": 'Delete "{titolo}"?',
  "val.errCrea": "Creation failed",
  "val.errDuplica": "Duplication failed",
  "val.revisioneIniziale": "REV 01",

  // JSON export / import
  "json.esporta": "Export JSON",
  "json.importa": "Import JSON",
  "json.esportato": "File exported: {nome}",
  "json.importato": "Assessment imported: {titolo}",
  "json.chiediAzienda":
    "The file contains details for the company «{nome}», which differ from the current ones.\n\nDo you also want to update the company settings (details and logo)?",
  "json.aziendaAggiornata": "Company settings updated.",
  "json.descrizioneFile": "PPWR assessment file",
  "json.errEsportazione": "Export failed",
  "json.errImportazione": "Import failed",
  "json.errFileNonJson": "The file is not valid JSON.",
  "json.errFormato": "The file does not comply with the PPWR standard.",
  "json.errVersione": "Unsupported file version: expected {v}.",
  "json.errCampi": "Title, date or a valid list of components is missing.",
  "json.errComponente": "Component no. {n} has an invalid weight or recyclability index.",
  "json.errTroppoGrande": "The file is too large (max 5 MB).",

  "demo.bottiglia": "Bottle",
  "demo.tappo": "Cap",
  "demo.etichetta": "Label",
  "demo.cartaMetallizzata": "Metallised paper",

  "ed.titoloPagina": "Assessment editor — PPWR Recyclability",
  "ed.esporta": "Export report",
  "ed.salvato": "✓ saved online",
  "ed.errSalvataggio": "save error",
  "ed.riprova": "Retry now",
  "ed.nuovoTentativo": "retrying…",
  "ed.salvataggio": "saving…",
  "ed.componenti": "Components — mass balance",
  "ed.righe": "{n} rows · total mass {peso} g",
  "ed.colComponente": "Component",
  "ed.colMateriale": "Material",
  "ed.colPeso": "Weight (g)",
  "ed.colPercRicic": "% recycl.",
  "ed.colMassaRicic": "Recycl. mass (g)",
  "ed.totale": "Total",
  "ed.aggiungi": "+ Add component",
  "ed.nuovoComponente": "New component",
  "ed.calcolata": "Calculated recyclability",
  "ed.gRiciclabili": "{m} g recyclable out of {t} g",
  "ed.sogliaMin": "Minimum eligibility threshold 2030:",
  "ed.soglie": "Annex II Table 3 thresholds",
  "ed.note": "Technical notes",
  "ed.notePlaceholder":
    "Calculation assumptions, references to the bill of materials, breakdown of complex components…",

  "rep.titoloPagina": "Recyclability report — PPWR Recyclability",
  "rep.stampa": "Download PDF",
  "ed.notaNumeri": "Numbers: you can type a point or a comma (converted to a point, e.g. 2.5), at most two decimals. Weight in grams; recyclable % from 0 to 100.",
  "rep.generazione": "Generating preview…",
  "rep.errPdf": "Unable to generate the PDF preview.",
  "rep.errScarica": "Unable to generate the PDF.",
  "rep.notaAnteprima": "The preview is read-only: Place, Date and signatory are filled in on the downloaded PDF.",
  "rep.norma": "Regulation (EU) 2025/40 (PPWR)",
  "rep.firmaTitolo": "Place, date and signature",
  "rep.luogo": "Place",
  "rep.data": "Date",
  "rep.firma": "Signature",
  "rep.pagina": "Page {n} of {tot}",
  "rep.anteprima": "Report preview",
  "rep.torna": "← back to editor",
  "rep.aziendaNonImpostata": "Company not set",
  "rep.aziendaNonImpostataMin": "company not set",
  "rep.piva": "VAT {v}",
  "rep.referente": "Contact: {v}",
  "rep.impostaDati": "Set company details",
  "rep.titolo": "Packaging recyclability assessment",
  "rep.intro":
    "This report determines the recyclability share, by weight, of the packaging in question pursuant to Regulation (EU) 2025/40 (PPWR). The percentage is calculated as the ratio between the mass of the recyclable components and the total mass of the packaging, according to the performance classes of Annex II, Table 3.",
  "rep.s1": "1. Mass balance",
  "rep.colIndice": "Index (%)",
  "rep.totaleImballaggio": "Total packaging",
  "rep.s2": "2. Calculation result",
  "rep.ricic": "Recyclability",
  "rep.statoAmmissibilita": "Eligibility status from 2030: {stato}",
  "rep.s3": "3. Performance classes (Annex II, Table 3)",
  "rep.s4": "4. Technical notes",
  "rep.footer":
    "Document generated for the technical file referred to in Annex VII of Reg. (EU) 2025/40 — {azienda}",
  "ed.etNome": "Packaging / product name",
  "ed.phNome": "e.g. Glass bottle, Toothpaste tube, 500 ml PET bottle",
  "ed.etRevisione": "Revision",
  "ed.etData": "Date",
  "ed.salva": "Save",
  "ed.salvataggioOk": "Assessment saved successfully!",
  "ed.chiediNomeTitolo": "Give the assessment a name",
  "ed.chiediNomeTesto":
    "To file the record correctly, enter the name of the packaging or product analysed:",
  "ed.annulla": "Cancel",
  "ed.confermaSalva": "Confirm and save",
  "ed.nomeObbligatorio": "Please enter a name other than “New assessment”.",

  "nav.guida": "Help",
  "guida.titoloPagina": "Guide — PPWR Recyclability",
  "guida.titolo": "User guide",
  "guida.intro": "How the program works, from the calculation to the PDF report.",
  "guida.sommario": "Contents",
  "guida.torna": "← back to the app",
  "guida.avviso": "Calculation support tool: always check grades and thresholds against the official text of Reg. (EU) 2025/40.",
  "hint.apri": "Show hint",
  "hint.revisione": "Document revision code, e.g. REV 01, REV 02. It appears in the report.",
  "hint.componente": "Part of the packaging: e.g. tank, valve, gasket, cap.",
  "hint.materiale": "Material designation: e.g. PET, HDPE, AISI 304, EPDM.",
  "hint.peso": "Mass of the component in grams. Point or comma, at most two decimals.",
  "hint.indice": "Recyclable share from 0 to 100. 100 for homogeneous materials with an EU recycling stream; 0 for elastomers, thermosets or mixed plastics with no stream; an intermediate value only if certified.",
  "hint.massa": "Calculated automatically: weight × recyclable % ÷ 100.",
  "hint.note": "Calculation assumptions, drawing codes, breakdown of assemblies, standards adopted. They appear in section 4 of the report.",
};

const de: Record<Chiave, string> = {
  "app.nome": "PPWR-Recyclingfähigkeit",
  "app.sottotitolo": "Bestimmung Recyclingfähigkeit in % · VO (EU) 2025/40",
  "nav.valutazioni": "Bewertungen",
  "nav.impostazioni": "Einstellungen",
  "nav.esci": "Abmelden",
  "nav.chiudiApp": "Anwendung schließen",
  "nav.esciCancella": "Abmelden und alles löschen",
  "lingua.etichetta": "Sprache",
  "comune.caricamento": "Wird geladen…",
  "comune.nonTrovata": "Bewertung nicht gefunden.",
  "comune.logoAlt": "Firmenlogo",
  "comune.sessioneScaduta": "Sitzung abgelaufen: Bitte melden Sie sich erneut an.",

  "grado.label": "Klasse",
  "grado.A": "Exzellenz",
  "grado.B": "Hohe Recyclingfähigkeit",
  "grado.C": "Mindestschwelle für die Zulässigkeit",
  "esito.nonConforme": "Nicht konform",
  "stato.ammesso": "Zulässig",
  "stato.nonAmmesso": "Nicht zulässig",

  "root.404": "Seite nicht gefunden",
  "root.404testo": "Die gesuchte Seite existiert nicht oder wurde verschoben.",
  "root.home": "Zur Startseite",
  "root.errTitolo": "Diese Seite konnte nicht geladen werden",
  "root.errTesto":
    "Etwas ist schiefgelaufen. Aktualisieren Sie die Seite oder kehren Sie zur Startseite zurück.",
  "root.riprova": "Erneut versuchen",

  "landing.titoloPagina":
    "PPWR-Recyclingfähigkeit — Berechnung der Recyclingklasse von Verpackungen",
  "landing.accedi": "App öffnen",
  "landing.kicker": "VO (EU) 2025/40 · Anhang II",
  "landing.titolo": "Recyclingfähigkeit von Verpackungen, berechnet und dokumentiert.",
  "landing.testo":
    "Setzen Sie die Verpackung aus ihren Komponenten zusammen, erhalten Sie den Massenanteil und die PPWR-Klasse in Echtzeit und exportieren Sie einen technischen Bericht mit Ihrem Firmenkopf. Alles wird online gespeichert und zwischen Ihren Geräten synchronisiert.",
  "landing.inizia": "Bewertung starten",


  "imp.titoloPagina": "Firmeneinstellungen — PPWR-Recyclingfähigkeit",
  "imp.titolo": "Daten des erstellenden Unternehmens",
  "imp.sotto": "werden im Berichtskopf verwendet",
  "imp.ragioneSociale": "Firmenname",
  "imp.partitaIva": "USt-IdNr.",
  "imp.sede": "Firmensitz",
  "imp.referente": "Technischer Ansprechpartner",
  "imp.email": "E-Mail / Kontakt",
  "imp.phRagioneSociale": "Firmenname GmbH",
  "imp.phPartitaIva": "IT00000000000",
  "imp.phSede": "Straße, PLZ, Ort",
  "imp.phReferente": "Name und Funktion",
  "imp.phEmail": "technik@firma.de",
  "imp.salva": "Firmendaten speichern",
  "imp.salvato": "Daten gespeichert",
  "imp.errSalvataggio": "Speichern fehlgeschlagen",
  "imp.logo": "Firmenlogo",
  "imp.nessunLogo": "Kein Logo hochgeladen",
  "imp.carica": "Bild hochladen",
  "imp.rimuovi": "Logo entfernen",
  "imp.logoTroppoGrande":
    "Das Logo ist größer als 1,5 MB: Bitte verwenden Sie eine kleinere Datei.",
  "imp.notaLogo":
    "PNG oder JPG, max. 1,5 MB. Daten und Logo werden online gespeichert und sind auf allen Ihren Geräten verfügbar.",

  "val.titoloPagina": "Recyclingfähigkeits-Bewertungen — PPWR-Recyclingfähigkeit",
  "val.nuova": "Neue Bewertung",
  "val.archivio": "Bewertungsarchiv",
  "val.documenti": "{n} Dokumente · online synchronisiert",
  "val.vuotoTitolo": "Keine Bewertungen vorhanden",
  "val.vuotoTesto":
    "Erstellen Sie Ihre erste Bewertung: Geben Sie die Verpackungskomponenten mit Gewicht und Recyclingindex ein, die PPWR-Klasse wird automatisch berechnet.",
  "val.colValutazione": "Bewertung",
  "val.colRevisione": "Revision",
  "val.colMassa": "Masse (g)",
  "val.colRicic": "Recyclingfähigkeit",
  "val.colGrado": "Klasse",
  "val.report": "Bericht",
  "val.modifica": "Bearbeiten",
  "val.duplica": "Duplizieren",
  "val.elimina": "Löschen",
  "val.copia": "{titolo} (Kopie)",
  "val.confermaElimina": '„{titolo}" löschen?',
  "val.errCrea": "Erstellung fehlgeschlagen",
  "val.errDuplica": "Duplizierung fehlgeschlagen",
  "val.revisioneIniziale": "REV 01",

  // JSON-Export / -Import
  "json.esporta": "JSON exportieren",
  "json.importa": "JSON importieren",
  "json.esportato": "Datei exportiert: {nome}",
  "json.importato": "Bewertung importiert: {titolo}",
  "json.chiediAzienda":
    "Die Datei enthält Daten des Unternehmens «{nome}», die von den aktuellen abweichen.\n\nMöchten Sie auch die Firmeneinstellungen (Daten und Logo) aktualisieren?",
  "json.aziendaAggiornata": "Firmeneinstellungen aktualisiert.",
  "json.descrizioneFile": "PPWR-Bewertungsdatei",
  "json.errEsportazione": "Export fehlgeschlagen",
  "json.errImportazione": "Import fehlgeschlagen",
  "json.errFileNonJson": "Die Datei ist kein gültiges JSON.",
  "json.errFormato": "Die Datei entspricht nicht dem PPWR-Standard.",
  "json.errVersione": "Nicht unterstützte Dateiversion: erwartet {v}.",
  "json.errCampi": "Titel, Datum oder eine gültige Komponentenliste fehlen.",
  "json.errComponente":
    "Komponente Nr. {n} hat ein ungültiges Gewicht oder einen ungültigen Recyclingindex.",
  "json.errTroppoGrande": "Die Datei ist zu groß (max. 5 MB).",

  "demo.bottiglia": "Flasche",
  "demo.tappo": "Verschluss",
  "demo.etichetta": "Etikett",
  "demo.cartaMetallizzata": "Metallisiertes Papier",

  "ed.titoloPagina": "Bewertungseditor — PPWR-Recyclingfähigkeit",
  "ed.esporta": "Bericht exportieren",
  "ed.salvato": "✓ online gespeichert",
  "ed.errSalvataggio": "Speicherfehler",
  "ed.riprova": "Jetzt erneut versuchen",
  "ed.nuovoTentativo": "neuer Versuch…",
  "ed.salvataggio": "wird gespeichert…",
  "ed.componenti": "Komponenten — Massenbilanz",
  "ed.righe": "{n} Zeilen · Gesamtmasse {peso} g",
  "ed.colComponente": "Komponente",
  "ed.colMateriale": "Material",
  "ed.colPeso": "Gewicht (g)",
  "ed.colPercRicic": "% recycl.",
  "ed.colMassaRicic": "Recycl. Masse (g)",
  "ed.totale": "Gesamt",
  "ed.aggiungi": "+ Komponente hinzufügen",
  "ed.nuovoComponente": "Neue Komponente",
  "ed.calcolata": "Berechnete Recyclingfähigkeit",
  "ed.gRiciclabili": "{m} g recycelbar von {t} g",
  "ed.sogliaMin": "Mindestschwelle für die Zulässigkeit 2030:",
  "ed.soglie": "Schwellenwerte Anhang II Tab. 3",
  "ed.note": "Technische Hinweise",
  "ed.notePlaceholder":
    "Berechnungsannahmen, Verweise auf die Stückliste, Aufschlüsselung komplexer Komponenten…",

  "rep.titoloPagina": "Recyclingfähigkeitsbericht — PPWR-Recyclingfähigkeit",
  "rep.stampa": "PDF herunterladen",
  "ed.notaNumeri": "Zahlen: Punkt oder Komma möglich (wird in ein Komma umgewandelt, z. B. 2,5), höchstens zwei Nachkommastellen. Gewicht in Gramm; recycelbarer Anteil von 0 bis 100 %.",
  "rep.generazione": "Vorschau wird erstellt…",
  "rep.errPdf": "Die PDF-Vorschau konnte nicht erstellt werden.",
  "rep.errScarica": "Das PDF konnte nicht erstellt werden.",
  "rep.notaAnteprima": "Die Vorschau ist schreibgeschützt: Ort, Datum und Unterzeichner werden im heruntergeladenen PDF ausgefüllt.",
  "rep.norma": "Verordnung (EU) 2025/40 (PPWR)",
  "rep.firmaTitolo": "Ort, Datum und Unterschrift",
  "rep.luogo": "Ort",
  "rep.data": "Datum",
  "rep.firma": "Unterschrift",
  "rep.pagina": "Seite {n} von {tot}",
  "rep.anteprima": "Berichtsvorschau",
  "rep.torna": "← zurück zum Editor",
  "rep.aziendaNonImpostata": "Unternehmen nicht festgelegt",
  "rep.aziendaNonImpostataMin": "Unternehmen nicht festgelegt",
  "rep.piva": "USt-IdNr. {v}",
  "rep.referente": "Ansprechpartner: {v}",
  "rep.impostaDati": "Firmendaten festlegen",
  "rep.titolo": "Bewertung der Recyclingfähigkeit der Verpackung",
  "rep.intro":
    "Dieser Bericht ermittelt den gewichtsbezogenen Anteil der Recyclingfähigkeit der betreffenden Verpackung gemäß Verordnung (EU) 2025/40 (PPWR). Der Prozentsatz wird als Verhältnis der Masse der recycelbaren Komponenten zur Gesamtmasse der Verpackung berechnet, gemäß den Leistungsklassen in Anhang II, Tabelle 3.",
  "rep.s1": "1. Massenbilanz",
  "rep.colIndice": "Index (%)",
  "rep.totaleImballaggio": "Verpackung gesamt",
  "rep.s2": "2. Berechnungsergebnis",
  "rep.ricic": "Recyclingfähigkeit",
  "rep.statoAmmissibilita": "Zulässigkeitsstatus ab 2030: {stato}",
  "rep.s3": "3. Leistungsklassen (Anhang II, Tabelle 3)",
  "rep.s4": "4. Technische Hinweise",
  "rep.footer":
    "Dokument erstellt für die technische Dokumentation gemäß Anhang VII der VO (EU) 2025/40 — {azienda}",
  "ed.etNome": "Name der Verpackung / des Produkts",
  "ed.phNome": "z. B. Glasflasche, Zahnpastatube, PET-Flasche 500 ml",
  "ed.etRevisione": "Revision",
  "ed.etData": "Datum",
  "ed.salva": "Speichern",
  "ed.salvataggioOk": "Bewertung erfolgreich gespeichert!",
  "ed.chiediNomeTitolo": "Geben Sie der Bewertung einen Namen",
  "ed.chiediNomeTesto":
    "Bitte geben Sie den Namen der analysierten Verpackung oder des Produkts ein, damit das Datenblatt korrekt archiviert wird:",
  "ed.annulla": "Abbrechen",
  "ed.confermaSalva": "Bestätigen und speichern",
  "ed.nomeObbligatorio": "Bitte geben Sie einen anderen Namen als „Neue Bewertung“ ein.",

  "nav.guida": "Hilfe",
  "guida.titoloPagina": "Anleitung — PPWR-Recyclingfähigkeit",
  "guida.titolo": "Bedienungsanleitung",
  "guida.intro": "So funktioniert das Programm, von der Berechnung bis zum PDF-Bericht.",
  "guida.sommario": "Inhalt",
  "guida.torna": "← zurück zur App",
  "guida.avviso": "Hilfsmittel zur Berechnung: Klassen und Schwellenwerte immer am offiziellen Text der Verordnung (EU) 2025/40 prüfen.",
  "hint.apri": "Hinweis anzeigen",
  "hint.revisione": "Revisionscode des Dokuments, z. B. REV 01, REV 02. Erscheint im Bericht.",
  "hint.componente": "Teil der Verpackung: z. B. Tank, Ventil, Dichtung, Verschluss.",
  "hint.materiale": "Werkstoffbezeichnung: z. B. PET, HDPE, AISI 304, EPDM.",
  "hint.peso": "Masse des Bauteils in Gramm. Punkt oder Komma, höchstens zwei Nachkommastellen.",
  "hint.indice": "Recycelbarer Anteil von 0 bis 100. 100 für homogene Werkstoffe mit EU-Recyclingkette; 0 für Elastomere, Duroplaste oder Mischkunststoffe ohne Kette; ein Zwischenwert nur bei Zertifizierung.",
  "hint.massa": "Wird automatisch berechnet: Gewicht × recycelbarer Anteil in % ÷ 100.",
  "hint.note": "Berechnungsannahmen, Zeichnungsnummern, Zerlegung von Baugruppen, angewandte Normen. Sie erscheinen in Abschnitt 4 des Berichts.",
};

const es: Record<Chiave, string> = {
  "app.nome": "Reciclabilidad PPWR",
  "app.sottotitolo": "Determinación del % de reciclabilidad · Reg. (UE) 2025/40",
  "nav.valutazioni": "Evaluaciones",
  "nav.impostazioni": "Ajustes",
  "nav.esci": "Cerrar sesión",
  "nav.chiudiApp": "Cerrar aplicación",
  "nav.esciCancella": "Salir y borrar todo",
  "lingua.etichetta": "Idioma",
  "comune.caricamento": "Cargando…",
  "comune.nonTrovata": "Evaluación no encontrada.",
  "comune.logoAlt": "Logotipo de la empresa",
  "comune.sessioneScaduta": "Sesión caducada: vuelve a iniciar sesión.",

  "grado.label": "Grado",
  "grado.A": "Excelencia",
  "grado.B": "Alta reciclabilidad",
  "grado.C": "Umbral mínimo de admisibilidad",
  "esito.nonConforme": "No conforme",
  "stato.ammesso": "Admitido",
  "stato.nonAmmesso": "No admitido",

  "root.404": "Página no encontrada",
  "root.404testo": "La página que buscas no existe o ha sido movida.",
  "root.home": "Ir al inicio",
  "root.errTitolo": "Esta página no se ha cargado",
  "root.errTesto": "Algo ha salido mal. Prueba a actualizar la página o vuelve al inicio.",
  "root.riprova": "Reintentar",

  "landing.titoloPagina": "Reciclabilidad PPWR — Cálculo del grado de reciclabilidad de envases",
  "landing.accedi": "Acceder a la app",
  "landing.kicker": "Reg. (UE) 2025/40 · Anexo II",
  "landing.titolo": "Reciclabilidad de los envases, calculada y documentada.",
  "landing.testo":
    "Compón el envase por componentes, obtén el porcentaje en masa y el grado PPWR en tiempo real y exporta un informe técnico con el membrete de tu empresa. Todo se guarda en línea y se sincroniza entre tus dispositivos.",
  "landing.inizia": "Iniciar una evaluación",


  "imp.titoloPagina": "Ajustes de la empresa — Reciclabilidad PPWR",
  "imp.titolo": "Datos de la empresa que elabora el informe",
  "imp.sotto": "se usan en el membrete de los informes",
  "imp.ragioneSociale": "Razón social",
  "imp.partitaIva": "NIF / IVA",
  "imp.sede": "Domicilio",
  "imp.referente": "Responsable técnico",
  "imp.email": "Correo / contacto",
  "imp.phRagioneSociale": "Nombre de la empresa S.L.",
  "imp.phPartitaIva": "IT00000000000",
  "imp.phSede": "Calle, código postal, ciudad",
  "imp.phReferente": "Nombre y cargo",
  "imp.phEmail": "tecnico@empresa.es",
  "imp.salva": "Guardar datos de la empresa",
  "imp.salvato": "Datos guardados",
  "imp.errSalvataggio": "No se pudo guardar",
  "imp.logo": "Logotipo de la empresa",
  "imp.nessunLogo": "Ningún logotipo cargado",
  "imp.carica": "Subir imagen",
  "imp.rimuovi": "Quitar logotipo",
  "imp.logoTroppoGrande": "El logotipo supera 1,5 MB: usa un archivo más ligero.",
  "imp.notaLogo":
    "PNG o JPG, máx. 1,5 MB. Los datos y el logotipo se guardan en línea y están disponibles en todos tus dispositivos.",

  "val.titoloPagina": "Evaluaciones de reciclabilidad — Reciclabilidad PPWR",
  "val.nuova": "Nueva evaluación",
  "val.archivio": "Archivo de evaluaciones",
  "val.documenti": "{n} documentos · sincronizados en línea",
  "val.vuotoTitolo": "No hay evaluaciones",
  "val.vuotoTesto":
    "Crea la primera evaluación: introduce los componentes del envase con su peso e índice de reciclabilidad y el grado PPWR se calcula automáticamente.",
  "val.colValutazione": "Evaluación",
  "val.colRevisione": "Revisión",
  "val.colMassa": "Masa (g)",
  "val.colRicic": "Reciclabilidad",
  "val.colGrado": "Grado",
  "val.report": "Informe",
  "val.modifica": "Editar",
  "val.duplica": "Duplicar",
  "val.elimina": "Eliminar",
  "val.copia": "{titolo} (copia)",
  "val.confermaElimina": '¿Eliminar "{titolo}"?',
  "val.errCrea": "No se pudo crear",
  "val.errDuplica": "No se pudo duplicar",
  "val.revisioneIniziale": "REV 01",

  // Exportación / importación JSON
  "json.esporta": "Exportar JSON",
  "json.importa": "Importar JSON",
  "json.esportato": "Archivo exportado: {nome}",
  "json.importato": "Evaluación importada: {titolo}",
  "json.chiediAzienda":
    "El archivo contiene datos de la empresa «{nome}», distintos de los actuales.\n\n¿Quieres actualizar también los ajustes de la empresa (datos y logotipo)?",
  "json.aziendaAggiornata": "Ajustes de la empresa actualizados.",
  "json.descrizioneFile": "Archivo de evaluación PPWR",
  "json.errEsportazione": "No se pudo exportar",
  "json.errImportazione": "No se pudo importar",
  "json.errFileNonJson": "El archivo no es un JSON válido.",
  "json.errFormato": "El archivo no cumple el estándar PPWR.",
  "json.errVersione": "Versión de archivo no admitida: se esperaba {v}.",
  "json.errCampi": "Falta el título, la fecha o una lista de componentes válida.",
  "json.errComponente":
    "El componente n.º {n} tiene un peso o un índice de reciclabilidad no válidos.",
  "json.errTroppoGrande": "El archivo es demasiado grande (máx. 5 MB).",

  "demo.bottiglia": "Botella",
  "demo.tappo": "Tapón",
  "demo.etichetta": "Etiqueta",
  "demo.cartaMetallizzata": "Papel metalizado",

  "ed.titoloPagina": "Editor de evaluación — Reciclabilidad PPWR",
  "ed.esporta": "Exportar informe",
  "ed.salvato": "✓ guardado en línea",
  "ed.errSalvataggio": "error al guardar",
  "ed.riprova": "Reintentar ahora",
  "ed.nuovoTentativo": "nuevo intento…",
  "ed.salvataggio": "guardando…",
  "ed.componenti": "Componentes — balance de masa",
  "ed.righe": "{n} filas · masa total {peso} g",
  "ed.colComponente": "Componente",
  "ed.colMateriale": "Material",
  "ed.colPeso": "Peso (g)",
  "ed.colPercRicic": "% recic.",
  "ed.colMassaRicic": "Masa recic. (g)",
  "ed.totale": "Total",
  "ed.aggiungi": "+ Añadir componente",
  "ed.nuovoComponente": "Nuevo componente",
  "ed.calcolata": "Reciclabilidad calculada",
  "ed.gRiciclabili": "{m} g reciclables de {t} g",
  "ed.sogliaMin": "Umbral mínimo de admisibilidad 2030:",
  "ed.soglie": "Umbrales Anexo II Tabla 3",
  "ed.note": "Notas técnicas",
  "ed.notePlaceholder":
    "Hipótesis de cálculo, referencias a la lista de materiales, desglose de componentes complejos…",

  "rep.titoloPagina": "Informe de reciclabilidad — Reciclabilidad PPWR",
  "rep.stampa": "Descargar PDF",
  "ed.notaNumeri": "Números: puedes escribir punto o coma (se convierte en coma, p. ej. 2,5), como máximo dos decimales. Peso en gramos; % reciclable de 0 a 100.",
  "rep.generazione": "Generando la vista previa…",
  "rep.errPdf": "No se pudo generar la vista previa del PDF.",
  "rep.errScarica": "No se pudo generar el PDF.",
  "rep.notaAnteprima": "La vista previa es de solo lectura: Lugar, Fecha y firmante se rellenan en el PDF descargado.",
  "rep.norma": "Reglamento (UE) 2025/40 (PPWR)",
  "rep.firmaTitolo": "Lugar, fecha y firma",
  "rep.luogo": "Lugar",
  "rep.data": "Fecha",
  "rep.firma": "Firma",
  "rep.pagina": "Página {n} de {tot}",
  "rep.anteprima": "Vista previa del informe",
  "rep.torna": "← volver al editor",
  "rep.aziendaNonImpostata": "Empresa no configurada",
  "rep.aziendaNonImpostataMin": "empresa no configurada",
  "rep.piva": "NIF/IVA {v}",
  "rep.referente": "Responsable: {v}",
  "rep.impostaDati": "Configurar datos de la empresa",
  "rep.titolo": "Evaluación de la reciclabilidad del envase",
  "rep.intro":
    "El presente informe determina la cuota de reciclabilidad en peso del envase de referencia con arreglo al Reglamento (UE) 2025/40 (PPWR). El porcentaje se calcula como la relación entre la masa de los componentes reciclables y la masa total del envase, según las clases de rendimiento del Anexo II, Tabla 3.",
  "rep.s1": "1. Balance de masa",
  "rep.colIndice": "Índice (%)",
  "rep.totaleImballaggio": "Total del envase",
  "rep.s2": "2. Resultado del cálculo",
  "rep.ricic": "Reciclabilidad",
  "rep.statoAmmissibilita": "Estado de admisibilidad desde 2030: {stato}",
  "rep.s3": "3. Clases de rendimiento (Anexo II, Tabla 3)",
  "rep.s4": "4. Notas técnicas",
  "rep.footer":
    "Documento generado para el expediente técnico previsto en el Anexo VII del Reg. (UE) 2025/40 — {azienda}",
  "ed.etNome": "Nombre del envase / producto",
  "ed.phNome": "p. ej. Botella de vidrio, Tubo de dentífrico, Frasco PET 500 ml",
  "ed.etRevisione": "Revisión",
  "ed.etData": "Fecha",
  "ed.salva": "Guardar",
  "ed.salvataggioOk": "¡Evaluación guardada correctamente!",
  "ed.chiediNomeTitolo": "Asigna un nombre a la evaluación",
  "ed.chiediNomeTesto":
    "Para archivar correctamente la ficha, introduce el nombre del envase o producto analizado:",
  "ed.annulla": "Cancelar",
  "ed.confermaSalva": "Confirmar y guardar",
  "ed.nomeObbligatorio": "Introduce un nombre distinto de «Nueva evaluación».",

  "nav.guida": "Ayuda",
  "guida.titoloPagina": "Guía — Reciclabilidad PPWR",
  "guida.titolo": "Guía de uso",
  "guida.intro": "Cómo funciona el programa, desde el cálculo hasta el informe en PDF.",
  "guida.sommario": "Índice",
  "guida.torna": "← volver a la app",
  "guida.avviso": "Herramienta de apoyo al cálculo: comprueba siempre las clases y los umbrales en el texto oficial del Reg. (UE) 2025/40.",
  "hint.apri": "Mostrar sugerencia",
  "hint.revisione": "Código de revisión del documento, p. ej. REV 01, REV 02. Aparece en el informe.",
  "hint.componente": "Parte del embalaje: p. ej. depósito, válvula, junta, tapón.",
  "hint.materiale": "Designación del material: p. ej. PET, HDPE, AISI 304, EPDM.",
  "hint.peso": "Masa del componente en gramos. Punto o coma, como máximo dos decimales.",
  "hint.indice": "Parte reciclable de 0 a 100. 100 para materiales homogéneos con cadena de reciclaje en la UE; 0 para elastómeros, termoestables o plásticos mezclados sin cadena; un valor intermedio solo si está certificado.",
  "hint.massa": "Se calcula automáticamente: peso × % reciclable ÷ 100.",
  "hint.note": "Hipótesis de cálculo, códigos de plano, desglose de conjuntos, normas adoptadas. Aparecen en la sección 4 del informe.",
};

export const TRADUZIONI: Record<Lingua, Record<Chiave, string>> = { it, en, de, es };
