/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AttivazioneRouteImport } from './routes/attivazione'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CondizioniRouteImport } from './routes/condizioni'
import { Route as GuidaRouteImport } from './routes/guida'
import { Route as LicenzaScadutaRouteImport } from './routes/licenza-scaduta'
import { Route as AuthenticatedImpostazioniRouteImport } from './routes/_authenticated/impostazioni'
import { Route as AuthenticatedValutazioniRouteImport } from './routes/_authenticated/valutazioni'
import { Route as AuthenticatedReportIdRouteImport } from './routes/_authenticated/report.$id'
import { Route as AuthenticatedValutazioneIdRouteImport } from './routes/_authenticated/valutazione.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivazioneRoute = AttivazioneRouteImport.update({
  id: '/attivazione',
  path: '/attivazione',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CondizioniRoute = CondizioniRouteImport.update({
  id: '/condizioni',
  path: '/condizioni',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidaRoute = GuidaRouteImport.update({
  id: '/guida',
  path: '/guida',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenzaScadutaRoute = LicenzaScadutaRouteImport.update({
  id: '/licenza-scaduta',
  path: '/licenza-scaduta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedImpostazioniRoute =
  AuthenticatedImpostazioniRouteImport.update({
    id: '/impostazioni',
    path: '/impostazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedValutazioniRoute =
  AuthenticatedValutazioniRouteImport.update({
    id: '/valutazioni',
    path: '/valutazioni',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportIdRoute = AuthenticatedReportIdRouteImport.update({
  id: '/report/$id',
  path: '/report/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedValutazioneIdRoute =
  AuthenticatedValutazioneIdRouteImport.update({
    id: '/valutazione/$id',
    path: '/valutazione/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/guida': typeof GuidaRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/valutazioni': typeof AuthenticatedValutazioniRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/valutazione/$id': typeof AuthenticatedValutazioneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/guida': typeof GuidaRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/valutazioni': typeof AuthenticatedValutazioniRoute
  '/report/$id': typeof AuthenticatedReportIdRoute
  '/valutazione/$id': typeof AuthenticatedValutazioneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/attivazione': typeof AttivazioneRoute
  '/auth': typeof AuthRoute
  '/condizioni': typeof CondizioniRoute
  '/guida': typeof GuidaRoute
  '/licenza-scaduta': typeof LicenzaScadutaRoute
  '/_authenticated/impostazioni': typeof AuthenticatedImpostazioniRoute
  '/_authenticated/valutazioni': typeof AuthenticatedValutazioniRoute
  '/_authenticated/report/$id': typeof AuthenticatedReportIdRoute
  '/_authenticated/valutazione/$id': typeof AuthenticatedValutazioneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/guida'
    | '/licenza-scaduta'
    | '/impostazioni'
    | '/valutazioni'
    | '/report/$id'
    | '/valutazione/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/guida'
    | '/licenza-scaduta'
    | '/impostazioni'
    | '/valutazioni'
    | '/report/$id'
    | '/valutazione/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/attivazione'
    | '/auth'
    | '/condizioni'
    | '/guida'
    | '/licenza-scaduta'
    | '/_authenticated/impostazioni'
    | '/_authenticated/valutazioni'
    | '/_authenticated/report/$id'
    | '/_authenticated/valutazione/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AttivazioneRoute: typeof AttivazioneRoute
  AuthRoute: typeof AuthRoute
  CondizioniRoute: typeof CondizioniRoute
  GuidaRoute: typeof GuidaRoute
  LicenzaScadutaRoute: typeof LicenzaScadutaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivazione': {
      id: '/attivazione'
      path: '/attivazione'
      fullPath: '/attivazione'
      preLoaderRoute: typeof AttivazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condizioni': {
      id: '/condizioni'
      path: '/condizioni'
      fullPath: '/condizioni'
      preLoaderRoute: typeof CondizioniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guida': {
      id: '/guida'
      path: '/guida'
      fullPath: '/guida'
      preLoaderRoute: typeof GuidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenza-scaduta': {
      id: '/licenza-scaduta'
      path: '/licenza-scaduta'
      fullPath: '/licenza-scaduta'
      preLoaderRoute: typeof LicenzaScadutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/impostazioni': {
      id: '/_authenticated/impostazioni'
      path: '/impostazioni'
      fullPath: '/impostazioni'
      preLoaderRoute: typeof AuthenticatedImpostazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valutazioni': {
      id: '/_authenticated/valutazioni'
      path: '/valutazioni'
      fullPath: '/valutazioni'
      preLoaderRoute: typeof AuthenticatedValutazioniRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/report/$id': {
      id: '/_authenticated/report/$id'
      path: '/report/$id'
      fullPath: '/report/$id'
      preLoaderRoute: typeof AuthenticatedReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/valutazione/$id': {
      id: '/_authenticated/valutazione/$id'
      path: '/valutazione/$id'
      fullPath: '/valutazione/$id'
      preLoaderRoute: typeof AuthenticatedValutazioneIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedImpostazioniRoute: typeof AuthenticatedImpostazioniRoute
  AuthenticatedValutazioniRoute: typeof AuthenticatedValutazioniRoute
  AuthenticatedReportIdRoute: typeof AuthenticatedReportIdRoute
  AuthenticatedValutazioneIdRoute: typeof AuthenticatedValutazioneIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedImpostazioniRoute: AuthenticatedImpostazioniRoute,
  AuthenticatedValutazioniRoute: AuthenticatedValutazioniRoute,
  AuthenticatedReportIdRoute: AuthenticatedReportIdRoute,
  AuthenticatedValutazioneIdRoute: AuthenticatedValutazioneIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AttivazioneRoute: AttivazioneRoute,
  AuthRoute: AuthRoute,
  CondizioniRoute: CondizioniRoute,
  GuidaRoute: GuidaRoute,
  LicenzaScadutaRoute: LicenzaScadutaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
